name: Build/Push Image 

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DHURL: https://console.deployhub.com
      DHUSER: sdadmin
      DHPASS: 123456
      REGISTRY: quay.io
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set Convenience Env Vars
        id: env
        run: |
          echo "IMAGE_VERSION=1.0.${{ github.run_number }}-g$(echo ${{ github.sha }} | cut -c 1-6)" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.head_ref || github.ref_name }}-v1.0.${{ github.run_number }}-g$(echo ${{ github.sha }} | cut -c 1-6)" >> $GITHUB_ENV

      - name: Configure Git
        id: git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Login to Quay
        id: login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERID }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and Push Docker Image
        id: build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/ortelius/hello-world:${{ env.IMAGE_TAG }}

      - name: Generate SBOM
        id: sbom
        run: |
            curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
            ./syft packages ${{ env.REGISTRY }}/ortelius/hello-world:${{ env.IMAGE_TAG }} --scope all-layers -o cyclonedx-json > cyclonedx.json
            cat cyclonedx.json

      - name: Update Compnent 
        id: updatecomp
        run: |
          pip install ortelius-cli
          dh envscript --envvars component.toml --envvars_sh env.sh
          source env.sh
          dh updatecomp --rsp component.toml --deppkg cyclonedx@cyclonedx.json